## Nettoyage des datasets

1. Import des bibliothèques

In [4]:
from pathlib import Path
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

print("Librairies chargées ")

Librairies chargées

2. Chargement des datasets

In [7]:
data_path = Path.cwd().parent / "data" / "raw"
df1 = pd.read_csv(data_path / "data.csv", encoding="latin1")
df2 = pd.read_csv(data_path / "Train.csv", encoding="latin1")

print("Datasets chargés ✔")

Datasets chargés ✔

## DATASET 1 : data.csv

# Avant nettoyage

In [8]:
print("=== SHAPE ===")
print(df1.shape)

print("\n=== INFO ===")
print(df1.info())

print("\n=== MISSING VALUES ===")
print(df1.isnull().sum())

print("\n=== DUPLICATES ===")
print(df1.duplicated().sum())

print("\n=== SAMPLE ===")
display(df1.head())

=== SHAPE ===
(541909, 8)

=== INFO ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB
None

=== MISSING VALUES ===
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

=== DUPLICATES ===
5268

=== SAMPLE ===

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

# Nettoyage

In [9]:
df1_clean = df1.copy()

# supprimer doublons
df1_clean = df1_clean.drop_duplicates()

# gestion des valeurs manquantes
for col in df1_clean.columns:
    if df1_clean[col].dtype == "object":
        df1_clean[col].fillna("Unknown", inplace=True)
    else:
        df1_clean[col].fillna(df1_clean[col].median(), inplace=True)

# nettoyage noms colonnes
df1_clean.columns = df1_clean.columns.str.strip().str.lower().str.replace(" ", "_")

print("Nettoyage terminé ✔")

Nettoyage terminé ✔

C:\Users\Wiam Ougga\AppData\Local\Temp\ipykernel_22836\3735689542.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1_clean[col].fillna("Unknown", inplace=True)
C:\Users\Wiam Ougga\AppData\Local\Temp\ipykernel_22836\3735689542.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1_clean[col].fillna(df1_clean[col].median(), inplace=True)
C:\Users\Wiam Ougga\AppData\Local\Temp\ipykernel_22836\3735689542.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1_clean[col].fillna("Unknown", inplace=True)
C:\Users\Wiam Ougga\AppData\Local\Temp\ipykernel_22836\3735689542.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1_clean[col].fillna(df1_clean[col].median(), inplace=True)
C:\Users\Wiam Ougga\AppData\Local\Temp\ipykernel_22836\3735689542.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1_clean[col].fillna(df1_clean[col].median(), inplace=True)
C:\Users\Wiam Ougga\AppData\Local\Temp\ipykernel_22836\3735689542.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1_clean[col].fillna("Unknown", inplace=True)

# Aprés nettoyage

In [10]:
print("=== SHAPE ===")
print(df1_clean.shape)

print("\n=== MISSING VALUES ===")
print(df1_clean.isnull().sum())

print("\n=== DUPLICATES ===")
print(df1_clean.duplicated().sum())

display(df1_clean.head())

=== SHAPE ===
(536641, 8)

=== MISSING VALUES ===
invoiceno      0
stockcode      0
description    0
quantity       0
invoicedate    0
unitprice      0
customerid     0
country        0
dtype: int64

=== DUPLICATES ===
0

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

##DATASET 2 : Train.csv